perpustakaan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LoginStudentController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Dashboard\BookController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\BorrowController;
use App\Http\Controllers\Dashboard\ReturnController;
use App\Http\Controllers\Dashboard\StudentController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\CategoryBookController;
use App\Http\Controllers\Student\BookController as StudentBookController;
use App\Http\Controllers\Student\BorrowHistoryController;
use App\Http\Controllers\Student\DashboardController as StudentDashboardController;
use App\Http\Controllers\Student\UserController as StudentUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/book', [HomeController::class, 'book'])->name('book');
Route::get('/book/detail/{slug}', [HomeController::class, 'detail_book'])->name('detail-book');
Route::get('/category-book/{id}', [HomeController::class, 'category_book'])->name('category-book');
Route::get('/search-book', [HomeController::class, 'search_book'])->name('search-book');

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register-student', [RegisterController::class, 'registerProcess'])->name('registerProcess');

Route::get('/login-student', [LoginStudentController::class, 'login'])->name('login-student');
Route::post('/authenticate-student', [LoginStudentController::class, 'authenticate'])->name('authenticate-student');

Route::group(['middleware' => ['auth:user']], function() {
    Route::prefix('/admin')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.admin');
        Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

        Route::resource('/category-book', CategoryBookController::class);
        Route::resource('/book', BookController::class);
        Route::resource('/student', StudentController::class);
        Route::resource('/borrow', BorrowController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/return', ReturnController::class);
    });
});

Route::group(['middleware' => ['auth:student']], function() {
    Route::prefix('/student')->group(function() {
        Route::get('/dashboard', [StudentDashboardController::class, 'index'])->name('dashboard.siswa');
        Route::post('/logout-student', [LoginStudentController::class, 'logout'])->name('logout-student');

        Route::resource('/user-student', StudentUserController::class);
        Route::resource('/book-student', StudentBookController::class);
        Route::resource('/borrow-history', BorrowHistoryController::class);
    });
});

perpustakaan/app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'image',
        'category_book_id',
        'slug',
        'judul',
        'penerbit',
        'pengarang',
        'tahun',
        'lokasi',
        'stok',
        'keterangan',
    ];

    public function category_books()
    {
        return $this->belongsTo(CategoryBook::class, 'category_book_id');
    }

    public function peminjaman()
    {
        return $this->hasMany(Borrow::class);
    }
}

perpustakaan/app/Http/Controllers/Dashboard/BookController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Book;
use Illuminate\Support\Str;
use App\Models\CategoryBook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class BookController extends Controller
{
    public function index()
    {
        // $books = Book::orderBy('id', 'DESC')->get();

        $bukuDenganPeminjam = Book::with('peminjaman.students')->get();

        // foreach ($bukuDenganPeminjam as $buku) {
        //     echo "Judul Buku : " . $buku->judul . "\n";

        //     foreach ($buku->peminjaman as $peminjaman) {
        //     echo "Peminjam: " . $peminjaman->students->nama . "\n";
        //     echo "Tanggal Pinjam: " . $peminjaman->peminjaman . "\n";
        //     // ...
        //     }
        // }

        return view('dashboard.book.index', compact('bukuDenganPeminjam'));
    }

    public function create()
    {
        $category_books = CategoryBook::orderBy('nama_kategori', 'ASC')->get();

        return view('dashboard.book.create', compact('category_books'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'image' => 'required|image|file|max:2048|mimes:jpg,jpeg,png',
            'category_book_id' => 'required|integer',
            'judul' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'tahun' => 'required|max:4',
            'lokasi' => 'required',
            'stok' => 'required',
            'keterangan' => 'required',
        ]);

        $extension = $request->file('image')->getClientOriginalExtension();
        $imageName = Str::slug($request->judul) . rand() . '.' . $extension;
        $path = $request->file('image')->storeAs('cover-books', $imageName, 'public');

        $book = Book::create([
            'image' => $imageName,
            'category_book_id' => $request->category_book_id,
            'judul' => $request->judul,
            'slug' => Str::slug($request->judul),
            'penerbit' => $request->penerbit,
            'pengarang' => $request->pengarang,
            'tahun' => $request->tahun,
            'lokasi' => $request->lokasi,
            'stok' => $request->stok,
            'keterangan' => $request->keterangan,
        ]);

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Tambahkan');
    }

    public function show($id)
    {
        $b = Book::find($id);

        return view('dashboard.book.show', compact('b'));
    }

    public function edit($id)
    {
        $b = Book::find($id);
        $category_books = CategoryBook::orderBy('nama_kategori', 'ASC')->get();

        return view('dashboard.book.edit', compact('b', 'category_books'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'image' => 'nullable|image|file|max:2048|mimes:jpg,jpeg,png',
            'category_book_id' => 'required|integer',
            'judul' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'tahun' => 'required|max:4'
        ]);

        $book = Book::find($id);

        if ($request->image) {
            $imageOld = 'storage/cover-books/' . $book->image;
            if (File::exists($imageOld)) {
                File::delete($imageOld);

                $extension = $request->file('image')->getClientOriginalExtension();
                $imageName = rand() . '.' . $extension;
                $path = $request->file('image')->storeAs('cover-books', $imageName, 'public');
            }
        } else {
            $imageName = $book->image;
        }

        $book = Book::find($id)->update([
            'image' => $imageName,
            'category_book_id' => $request->category_book_id,
            'judul' => $request->judul,
            'penerbit' => $request->penerbit,
            'pengarang' => $request->pengarang,
            'tahun' => $request->tahun
        ]);

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Update');
    }

    public function destroy($id)
    {
        $book = Book::findorfail($id);
        $imageOld = File::delete('storage/cover-books/' . $book->image);
        $book->delete();

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Hapus');
    }
}

perpustakaan/app/Http/Controllers/Student/BookController.php
<?php

namespace App\Http\Controllers\Student;

use App\Models\Book;
use App\Models\Student;
use App\Models\CategoryBook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Borrow;

class BookController extends Controller
{
    public function index()
    {
        $books = Book::orderBy('id', 'DESC')->get();

        return view('dashboard-student.book.index', compact('books'));
    }

    public function create()
    {
        $students = Student::all();
        $categories = CategoryBook::all();
        $books = Book::all();
        $peminjaman = date('d-F-Y');
        $pengembalian = date('d-F-Y', strtotime('+7 day', strtotime(date('d-m-Y'))));
        $status = 'Meminjam';
        $allow = 'Belum Disetujui';

        return view('dashboard-student.book.create-borrow', compact('students', 'categories', 'books', 'peminjaman', 'pengembalian', 'status', 'allow'));
    }

    public function store(Request $request)
    {
        $validator = $request->validate([
            'student_id' => 'required|integer',
            'book_id' => 'required|integer',
            'peminjaman' => 'required',
            'pengembalian' => 'required',
            'admin' => 'required',
            'status' => 'required',
        ]);

        $book = Book::where('id', $request->book_id)->pluck('stok')->first();

        if($request->book_id) {
            if($book === 0) {
                return back()->withErrors([
                    'error' => 'Buku yang anda pinjam stok nya sudah habis..!'
                ]);
            }
            Book::find($request->book_id)->decrement('stok');
        }

        $create_borrow = Borrow::create($validator);

        return redirect()->route('borrow-history.index')->with('status', 'Data Peminjaman Berhasil Ditambahkan');
    }

    public function show($id)
    {
        $b = Book::find($id);

        return view('dashboard-student.book.show', compact('b'));
    }
}

perpustakaan/resources/views/dashboard-student/book/create-borrow.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Pinjam Buku')
    
@section('content')
<div class="container">
    <div class="row mb-3">
        <div class="col-12">
            @error('error')
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ $message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            @enderror
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header">
                    <h5>Peminjaman Buku</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('book-student.store') }}" method="POST">
                        @csrf
                        <div class="row mb-3">
                            <div class="col-6">
                                <label for="student_id" class="form-label">Siswa</label>
                                <select name="student_id" id="student_id" class="form-control @error('student_id') is-invalid @enderror">
                                    <option value="{{ Auth::guard('student')->user()->id }}">{{ Auth::guard('student')->user()->nama }}</option> 
                                </select>
                                @error('student_id')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-6">
                                <label for="book_id" class="form-label">Buku</label>
                                <select name="book_id" id="book_id" class="form-control @error('book_id') is-invalid @enderror">
                                    <option selected hidden>Pilih Buku</option>
                                    @foreach ($books as $book)
                                        <option value="{{ $book->id }}">{{ $book->judul }}</option>
                                    @endforeach
                                </select>
                                @error('book_id')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <label for="peminjaman" class="form-label">Peminjaman</label>
                                <input type="text" name="peminjaman" value="{{ $peminjaman }}" id="peminjaman" class="form-control @error('peminjaman') @enderror" readonly>
                                @error('peminjaman')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-6">
                                <label for="pengembalian" class="form-label">Pengembalian</label>
                                <input type="text" name="pengembalian" value="{{ $pengembalian }}" id="pengembalian" class="form-control @error('pengembalian') @enderror" readonly>
                                @error('pengembalian')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <label for="admin" class="form-label">Status Disetujui Admin</label>
                                <input type="text" name="admin" value="{{ $allow }}" id="admin" class="form-control @error('admin') is-invalid @enderror" readonly>
                                @error('admin')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-6">
                                <label for="status" class="form-label">Status</label>
                                <input type="text" name="status" value="{{ $status }}" id="status" class="form-control @error('status') is-invalid @enderror" readonly>
                                @error('status')
                                    <div class="alert alert-danger mt-1 mb-1 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <button class="btn btn-primary float-end ms-3">Pinjam</button>
                                <a href="{{ route('book-student.index') }}" class="btn btn-secondary float-end">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

perpustakaan/resources/views/dashboard-student/book/edit.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Edit Buku')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card shadow">
                    <div class="card-header">
                        <h4>Edit Buku</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('book.update', $b->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="row mb-3">
                                <div class="col-6">
                                    <label for="image" class="form-label">Image</label>
                                    <input type="file" name="image" id="image"
                                        class="form-control @error('image') is-invalid @enderror">
                                    @error('image')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-6">
                                    <label for="category_book_id" class="form-label">Kategori</label>
                                    <select name="category_book_id" id="category_book_id"
                                        class="form-control @error('category_book_id') is-invalid @enderror">
                                        <option selected hidden>Pilih Kategori</option>
                                        @foreach ($category_books as $cb)
                                            @if ($b->category_book_id == $cb->id)
                                                <option value="{{ $cb->id }}" selected>{{ $cb->nama_kategori }}
                                                </option>
                                            @else
                                                <option value="{{ $cb->id }}">{{ $cb->nama_kategori }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                    @error('category_book_id')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <label for="judul" class="form-label">Judul</label>
                                    <input type="text" name="judul" value="{{ $b->judul }}" id="judul"
                                        class="form-control @error('judul') is-invalid @enderror">
                                    @error('judul')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-6">
                                    <label for="penerbit" class="form-label">Penerbit</label>
                                    <input type="text" name="penerbit" value="{{ $b->penerbit }}" id="penerbit"
                                        class="form-control @error('penerbit') is-invalid @enderror">
                                    @error('penerbit')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <label for="pengarang" class="form-label">Pengarang</label>
                                    <input type="text" name="pengarang" value="{{ $b->pengarang }}" id="pengarang"
                                        class="form-control @error('pengarang') is-invalid @enderror">
                                    @error('pengarang')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-6">
                                    <label for="tahun" class="form-label">Tahun</label>
                                    <input type="text" name="tahun" value="{{ $b->tahun }}" id="tahun"
                                        class="form-control @error('tahun') is-invalid @enderror">
                                    @error('tahun')
                                        <div class="alert alert-danger mb-2 mt-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">
                                    <label for="lokasi" class="form-label">Lokasi / Rak</label>
                                    <input type="text" name="lokasi" value="{{ $b->lokasi }}" id="lokasi"
                                        class="form-control @error('lokasi') is-invalid @enderror"
                                        placeholder="Input Lokasi / Rak Buku">
                                    @error('lokasi')
                                        <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col-6">
                                    <label for="stok" class="form-label">Stok</label>
                                    <input type="number" name="stok" value="{{ $b->stok }} id="stok"
                                        class="form-control @error('stok') is-invalid @enderror" placeholder="Input Stok">
                                    @error('stok')
                                        <div class="alert alert-danger mb-2 mt-2 p-2">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-12">
                                    <label for="keterangan" class="form-label">Keterangan</label>
                                    <textarea name="keterangan" id="keterangan" cols="30" rows="10"
                                        class="form-control @error('keterangan') is-invalid @enderror)" placeholder="Input Keterangan">{{ $b->keterangan }}</textarea>
                                </div>
                                @error('keterangan')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <button class="btn btn-primary float-end">Update</button>
                                    <a href="{{ route('book.index') }}"
                                        class="btn btn-secondary float-end me-3">Kembali</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

perpustakaan/resources/views/dashboard-student/book/index.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Data Buku')

@section('content')
    <div class="container">
        <div class="row mb-3">
            <div class="col-12">
                @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{ session('status') }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12">
                <div class="card shadow">
                    <div class="card-header ">
                        <h5 class="float-start">Data Buku</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Image</th>
                                        <th>Judul</th>
                                        <th>Penerbit</th>
                                        <th>Pengarang</th>
                                        <th>Stok</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $no = 1;
                                    @endphp
                                    @foreach ($books as $b)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td><img src="{{ url('storage/cover-books/', $b->image) }}" width="150"
                                                    alt="" class="img img-fluid img-thumbnail border-dark"></td>
                                            <td>{{ $b->judul }}</td>
                                            <td>{{ $b->penerbit }}</td>
                                            <td>{{ $b->pengarang }}</td>
                                            <td>{{ $b->stok }}</td>
                                            <td width="7%%">
                                                <a href="{{ route('book-student.show', $b->id) }}" class="btn btn-info">
                                                    <i class="fa-regular fa-pen-to-square"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

perpustakaan/resources/views/dashboard-student/book/show.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Detail Buku')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-header">
                    <h4>Detail Buku</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered">
                            <tbody>
                                <tr>
                                    <th>Image</th>
                                    <td><img src="{{ url('storage/cover-books/', $b->image) }}" width="200" alt=""
                                            class="img img-fluid img-thumbnail border-dark"></td>
                                </tr>
                                <tr>
                                    <th>Kategori</th>
                                    <td>{{ $b->category_books->nama_kategori }}</td>
                                </tr>
                                <tr>
                                    <th>Judul</th>
                                    <td>{{ $b->judul }}</td>
                                </tr>
                                <tr>
                                    <th>Penerbit</th>
                                    <td>{{ $b->penerbit }}</td>
                                </tr>
                                <tr>
                                    <th>Pengarang</th>
                                    <td>{{ $b->pengarang }}</td>
                                </tr>
                                <tr>
                                    <th>Tahun</th>
                                    <td>{{ $b->tahun }}</td>
                                </tr>
                                <tr>
                                    <th>Lokasi / Rak</th>
                                    <td>{{ $b->lokasi }}</td>
                                </tr>
                                <tr>
                                    <th>Stok</th>
                                    <td>{{ $b->stok }}</td>
                                </tr>
                                <tr>
                                    <th>Keterangan</th>
                                    <td>{{ $b->keterangan }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer  d-flex justify-content-between">
                    <a href="{{ route('book-student.create') }}" class="btn btn-primary">Pinjam Buku</a>
                    <a href="{{ route('book.index') }}" class="btn btn-secondary">Kembali</a>
                </div>
            </div>
        </div>
    </div>
@endsection