perpustakaan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LoginStudentController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Dashboard\BookController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\BorrowController;
use App\Http\Controllers\Dashboard\ReturnController;
use App\Http\Controllers\Dashboard\StudentController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\CategoryBookController;
use App\Http\Controllers\Student\BookController as StudentBookController;
use App\Http\Controllers\Student\BorrowHistoryController;
use App\Http\Controllers\Student\DashboardController as StudentDashboardController;
use App\Http\Controllers\Student\UserController as StudentUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/book', [HomeController::class, 'book'])->name('book');
Route::get('/book/detail/{slug}', [HomeController::class, 'detail_book'])->name('detail-book');
Route::get('/category-book/{id}', [HomeController::class, 'category_book'])->name('category-book');
Route::get('/search-book', [HomeController::class, 'search_book'])->name('search-book');

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register-student', [RegisterController::class, 'registerProcess'])->name('registerProcess');

Route::get('/login-student', [LoginStudentController::class, 'login'])->name('login-student');
Route::post('/authenticate-student', [LoginStudentController::class, 'authenticate'])->name('authenticate-student');

Route::group(['middleware' => ['auth:user']], function() {
    Route::prefix('/admin')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.admin');
        Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

        Route::resource('/category-book', CategoryBookController::class);
        Route::resource('/book', BookController::class);
        Route::resource('/student', StudentController::class);
        Route::resource('/borrow', BorrowController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/return', ReturnController::class);
    });
});

Route::group(['middleware' => ['auth:student']], function() {
    Route::prefix('/student')->group(function() {
        Route::get('/dashboard', [StudentDashboardController::class, 'index'])->name('dashboard.siswa');
        Route::post('/logout-student', [LoginStudentController::class, 'logout'])->name('logout-student');

        Route::resource('/user-student', StudentUserController::class);
        Route::resource('/book-student', StudentBookController::class);
        Route::resource('/borrow-history', BorrowHistoryController::class);
    });
});

perpustakaan/app/Http/Controllers/Dashboard/BookController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Book;
use Illuminate\Support\Str;
use App\Models\CategoryBook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class BookController extends Controller
{
    public function index()
    {
        // $books = Book::orderBy('id', 'DESC')->get();

        $bukuDenganPeminjam = Book::with('peminjaman.students')->get();

        // foreach ($bukuDenganPeminjam as $buku) {
        //     echo "Judul Buku : " . $buku->judul . "\n";

        //     foreach ($buku->peminjaman as $peminjaman) {
        //     echo "Peminjam: " . $peminjaman->students->nama . "\n";
        //     echo "Tanggal Pinjam: " . $peminjaman->peminjaman . "\n";
        //     // ...
        //     }
        // }

        return view('dashboard.book.index', compact('bukuDenganPeminjam'));
    }

    public function create()
    {
        $category_books = CategoryBook::orderBy('nama_kategori', 'ASC')->get();

        return view('dashboard.book.create', compact('category_books'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'image' => 'required|image|file|max:2048|mimes:jpg,jpeg,png',
            'category_book_id' => 'required|integer',
            'judul' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'tahun' => 'required|max:4',
            'lokasi' => 'required',
            'stok' => 'required',
            'keterangan' => 'required',
        ]);

        $extension = $request->file('image')->getClientOriginalExtension();
        $imageName = Str::slug($request->judul) . rand() . '.' . $extension;
        $path = $request->file('image')->storeAs('cover-books', $imageName, 'public');

        $book = Book::create([
            'image' => $imageName,
            'category_book_id' => $request->category_book_id,
            'judul' => $request->judul,
            'slug' => Str::slug($request->judul),
            'penerbit' => $request->penerbit,
            'pengarang' => $request->pengarang,
            'tahun' => $request->tahun,
            'lokasi' => $request->lokasi,
            'stok' => $request->stok,
            'keterangan' => $request->keterangan,
        ]);

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Tambahkan');
    }

    public function show($id)
    {
        $b = Book::find($id);

        return view('dashboard.book.show', compact('b'));
    }

    public function edit($id)
    {
        $b = Book::find($id);
        $category_books = CategoryBook::orderBy('nama_kategori', 'ASC')->get();

        return view('dashboard.book.edit', compact('b', 'category_books'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'image' => 'nullable|image|file|max:2048|mimes:jpg,jpeg,png',
            'category_book_id' => 'required|integer',
            'judul' => 'required',
            'penerbit' => 'required',
            'pengarang' => 'required',
            'tahun' => 'required|max:4'
        ]);

        $book = Book::find($id);

        if ($request->image) {
            $imageOld = 'storage/cover-books/' . $book->image;
            if (File::exists($imageOld)) {
                File::delete($imageOld);

                $extension = $request->file('image')->getClientOriginalExtension();
                $imageName = rand() . '.' . $extension;
                $path = $request->file('image')->storeAs('cover-books', $imageName, 'public');
            }
        } else {
            $imageName = $book->image;
        }

        $book = Book::find($id)->update([
            'image' => $imageName,
            'category_book_id' => $request->category_book_id,
            'judul' => $request->judul,
            'penerbit' => $request->penerbit,
            'pengarang' => $request->pengarang,
            'tahun' => $request->tahun
        ]);

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Update');
    }

    public function destroy($id)
    {
        $book = Book::findorfail($id);
        $imageOld = File::delete('storage/cover-books/' . $book->image);
        $book->delete();

        return redirect()->route('book.index')->with('status', 'Data Buku Berhasil Di Hapus');
    }
}

perpustakaan/app/Http/Controllers/Dashboard/BorrowController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Book;
use App\Models\Borrow;
use App\Models\Student;
use App\Models\CategoryBook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BorrowController extends Controller
{
    public function index()
    {
        $borrows = Borrow::orderBy('id', 'DESC')->get();

        return view('dashboard.borrow.index', compact('borrows'));
    }

    public function create()
    {
        // $b = Book::where('id', 1)->pluck('stok')->first();
        // dd($b);

        $students = Student::all();
        $categories = CategoryBook::all();
        $books = Book::all();
        $peminjaman = date('d-F-Y');
        $pengembalian = date('d-F-Y', strtotime('+7 day', strtotime(date('d-m-Y'))));
        $status = 'Meminjam';
        $disetujui = ['Belum Disetujui', 'Sudah Disetujui'];

        return view('dashboard.borrow.create', compact('students', 'categories', 'books', 'peminjaman', 'pengembalian', 'status', 'disetujui'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'student_id' => 'required|integer',
            'book_id' => 'required|integer',
            'peminjaman' => 'required',
            'pengembalian' => 'required',
            'admin' => 'required',
            'status' => 'required',
        ]);

        $book = Book::where('id', $request->book_id)->pluck('stok')->first();

        if ($request->book_id) {
            if ($book == 0) {
                return back()->withErrors([
                    'error' => 'Buku yang anda pinjam stok nya sudah habis..!'
                ]);
            }
            // dd($request->book_id);
            // Book::find($request->book_id)->increment('stok');
            Book::find($request->book_id)->decrement('stok');
        }

        $borrow = Borrow::create($validate);

        return redirect()->route('borrow.index')->with('status', 'Data Peminjaman Berhasil Ditambahkan');
    }

    public function edit($id)
    {
        $b = Borrow::findOrFail($id);
        $students = Student::all();
        $categories = CategoryBook::all();
        $books = Book::all();
        $peminjaman = date('d-F-Y');
        $pengembalian = date('d-F-Y', strtotime('+7 day', strtotime(date('d-m-Y'))));
        $status = ['Meminjam', 'Mengembalikan'];
        $disetujui = ['Belum Disetujui', 'Sudah Disetujui'];

        return view('dashboard.borrow.edit', compact('b', 'students', 'categories', 'books', 'peminjaman', 'pengembalian', 'status', 'disetujui'));
    }

    public function update(Request $request, $id)
    {
        $borrow = $validate = $request->validate([
            'student_id' => 'required|integer',
            'book_id' => 'required|integer',
            'peminjaman' => 'required',
            'pengembalian' => 'required',
            'admin' => 'required',
            'status' => 'required',
        ]);

        if ($request->status === 'Mengembalikan') {
            Book::find($request->book_id)->increment('stok');
        }

        $borrow = Borrow::findOrFail($id)->update($validate);

        return redirect()->route('borrow.index')->with('status', 'Data Peminjaman Berhasil Diubah');
    }

    public function destroy($id)
    {
        $borrow = Borrow::findOrFail($id);
        $borrow->delete();

        return redirect()->route('borrow.index')->with('status', 'Data Peminjaman Berhasil Dihapus');
    }


    // public function destroy($id)
    // {
    //     Borrow::findOrFail($id)->delete();

    //     return redirect()->route('borrow.index')->with('status', 'Data Peminjaman Berhasil Dihapus');
    // }
}

perpustakaan/app/Http/Controllers/Dashboard/CategoryBookController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\CategoryBook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryBookController extends Controller
{
    public function index()
    {
        $category_books = CategoryBook::orderBy('id', 'DESC')->get();

        return view('dashboard.category-book.index', compact('category_books'));
    }

    public function create()
    {
        return view('dashboard.category-book.create');
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'nama_kategori' => 'required',
        ]);

        $category_book = CategoryBook::create($validate);

        return redirect()->route('category-book.index')->with('status', 'Data Kategori Buku Berhasil Di Tambahkan');
    }

    public function edit($id)
    {
        $cb = CategoryBook::find($id);

        return view('dashboard.category-book.edit', compact('cb'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'nama_kategori' => 'required',
        ]);

        $category_book = CategoryBook::find($id)->update($validate);

        return redirect()->route('category-book.index')->with('status', 'Data Kategori Buku Berhasil Di Update');
    }

    public function destroy($id)
    {
        $category_book = CategoryBook::findOrFail($id);
        $category_book->delete();

        return redirect()->route('category-book.index')->with('status', 'Data Kategori Buku Berhasil Di Hapus');
    }


    // public function destroy($id)
    // {
    //     $category_book = CategoryBook::find($id)->delete();

    //     return redirect()->route('category-book.index')->with('status', 'Data Kategori Buku Berhasil Di Hapus');
    // }
}

perpustakaan/app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

perpustakaan/app/Http/Controllers/Dashboard/ReturnController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Borrow;
use Illuminate\Http\Request;

class ReturnController extends Controller
{
    public function index()
    {
        $borrows = Borrow::where('status', 'Mengembalikan')->get();

        return view('dashboard.return.index', compact('borrows'));
    }
}

perpustakaan/app/Http/Controllers/Dashboard/StudentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class StudentController extends Controller
{
    public function index()
    {
        $students = Student::orderBy('id', 'DESC')->get();

        return view('dashboard.student.index', compact('students'));
    }

    public function create()
    {
        return view('dashboard.student.create');
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'nama' => 'required',
            'nis' => 'required|unique:students,nis',
            'kelas' => 'required',
            'password' => 'required',
        ]);

        $student = Student::create([
            'nama' => $request->nama,
            'nis' => $request->nis,
            'kelas' => $request->kelas,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('student.index')->with('status', 'Data Siswa Berhasil Ditambahkan');
    }

    public function edit($id)
    {
        $s = Student::find($id);

        return view('dashboard.student.edit', compact('s'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'nama' => 'required',
            'nis' => 'required',
            'kelas' => 'required',
        ]);

        $student = Student::find($id)->update($validate);

        return redirect()->route('student.index')->with('status', 'Data Siswa Berhasil Di Update');
    }

    public function destroy($id)
    {
        $student = Student::findOrFail($id);
        $student->delete();

        return redirect()->route('student.index')->with('status', 'Data Siswa Berhasil Di Hapus');
    }
}

perpustakaan/app/Http/Controllers/Student/BorrowHistoryController.php
<?php

namespace App\Http\Controllers\Student;

use App\Models\Borrow;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class BorrowHistoryController extends Controller
{
    public function index()
    {

        $borrow_history = Borrow::where('student_id', Auth::guard('student')->user()->id)->get();
        $status = Borrow::where('student_id', Auth::guard('student')->user()->id)->where('admin', 'Belum Disetujui');

        // dd($status);

        return view('dashboard-student.borrow-history.index', compact('borrow_history', 'status'));
    }
}

perpustakaan/app/Http/Controllers/Student/DashboardController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard-student.index');
    }
}

perpustakaan/resources/views/dashboard/student/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Admin | Tambah Siswa')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header">
                    <h4>Tambah Siswa</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('student.store') }}" method="POST">
                        @csrf
                        <div class="row mb-3">
                            <div class="form-group col-md-6">
                                <label for="nama" class="form-label">Nama</label>
                                <input type="text" name="nama" id="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Input nama">
                                @error('nama')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label for="nis" class="form-label">NIS</label>
                                <input type="number" name="nis" id="nis" class="form-control @error('nis') is-invalid @enderror" placeholder="Input NIS">
                                @error('nis')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="kelas" class="form-label">Kelas</label>
                                <input type="text" name="kelas" id="kelas" class="form-control @error('kelas') is-invalid @enderror" placeholder="Input Kelas">
                                @error('kelas')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror 
                            </div>
                            <div class="col-md-6">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" name="password" id="password" class="form-control @error('password') is-invalid @enderror" placeholder="Input Password">
                                @error('password')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror 
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary float-end ms-3">Tambah</button>
                                <a href="{{ route('student.index') }}" class="btn btn-secondary float-end">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

perpustakaan/resources/views/dashboard/student/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Admin | Edit Siswa')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header">
                    <h4>Edit Siswa</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('student.update', $s->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row mb-3">
                            <div class="form-group col-md-12">
                                <label for="nama" class="form-label">Nama</label>
                                <input type="text" name="nama" value="{{ $s->nama }}" id="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Input nama">
                                @error('nama')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="form-group col-md-6">
                                <label for="nis" class="form-label">NIS</label>
                                <input type="number" name="nis" value="{{ $s->nis }}" id="nis" class="form-control @error('nis') is-invalid @enderror" placeholder="Input NIS">
                                @error('nis')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <label for="kelas" class="form-label">Kelas</label>
                                <input type="text" name="kelas" value="{{ $s->kelas }}" id="kelas" class="form-control @error('kelas') is-invalid @enderror" placeholder="Input Kelas">
                                @error('kelas')
                                    <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                                @enderror 
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary float-end ms-3">Update</button>
                                <a href="{{ route('student.index') }}" class="btn btn-secondary float-end">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

perpustakaan/resources/views/dashboard/student/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Admin | Data Siswa')

@section('content')
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-12">
                @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ session('status') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card shadow">
                    <div class="card-header d-flex justify-content-between">
                        <h4 class="fw-bold">Data Siswa</h4>
                        <a href="{{ route('student.create') }}" class="btn btn-primary ms-3 mb-2">Tambah</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover" id="dataTable" width="100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>NIS</th>
                                        <th>Kelas</th>
                                        <th width="13%">Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $no= 1;
                                    @endphp
                                    @foreach ($students as $s)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $s->nama }}</td>
                                        <td>{{ $s->nis }}</td>
                                        <td>{{ $s->kelas }}</td>
                                        <td width="14%">
                                            <a href="{{ route('student.edit', $s->id) }}" class="btn btn-warning">
                                                <i class="fa-regular fa-pen-to-square"></i>
                                            </a>
                                            <form action="{{ route('student.destroy', $s->id) }}" method="POST" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-danger"><i class="fa-sharp fa-solid fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection