perpustakaan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LoginStudentController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Dashboard\BookController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\BorrowController;
use App\Http\Controllers\Dashboard\ReturnController;
use App\Http\Controllers\Dashboard\StudentController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\CategoryBookController;
use App\Http\Controllers\Student\BookController as StudentBookController;
use App\Http\Controllers\Student\BorrowHistoryController;
use App\Http\Controllers\Student\DashboardController as StudentDashboardController;
use App\Http\Controllers\Student\UserController as StudentUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/book', [HomeController::class, 'book'])->name('book');
Route::get('/book/detail/{slug}', [HomeController::class, 'detail_book'])->name('detail-book');
Route::get('/category-book/{id}', [HomeController::class, 'category_book'])->name('category-book');
Route::get('/search-book', [HomeController::class, 'search_book'])->name('search-book');

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register-student', [RegisterController::class, 'registerProcess'])->name('registerProcess');

Route::get('/login-student', [LoginStudentController::class, 'login'])->name('login-student');
Route::post('/authenticate-student', [LoginStudentController::class, 'authenticate'])->name('authenticate-student');

Route::group(['middleware' => ['auth:user']], function() {
    Route::prefix('/admin')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.admin');
        Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

        Route::resource('/category-book', CategoryBookController::class);
        Route::resource('/book', BookController::class);
        Route::resource('/student', StudentController::class);
        Route::resource('/borrow', BorrowController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/return', ReturnController::class);
    });
});

Route::group(['middleware' => ['auth:student']], function() {
    Route::prefix('/student')->group(function() {
        Route::get('/dashboard', [StudentDashboardController::class, 'index'])->name('dashboard.siswa');
        Route::post('/logout-student', [LoginStudentController::class, 'logout'])->name('logout-student');

        Route::resource('/user-student', StudentUserController::class);
        Route::resource('/book-student', StudentBookController::class);
        Route::resource('/borrow-history', BorrowHistoryController::class);
    });
});

perpustakaan/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

perpustakaan/app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('dashboard.user.index', compact('users'));
    }

    public function create()
    {
        $statuses = ['Admin', 'Siswa'];

        return view('dashboard.user.create', compact('statuses'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required',
            'email' => 'required',
            'status' => 'required',
            'password' => 'required',
        ]);

        if($request->status == "Pilih Status") {
            return back()->withErrors([
                'error' => 'Harap pilih status dengan benar!',
            ]);
        };

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'status' => $request->status,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('user.index')->with('status', 'Data User Berhasil Ditambahkan');
    }

    public function edit($id)
    {
        $u = User::find($id);

        return view('dashboard.user.edit', compact('u'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'name' => 'required',
            'email' => 'required',
            'password' => 'nullable',
        ]);

        $user = User::find($id);
        $passwordOldInDatabase = $user->password;

        if($request->passwordOld && $request->password) {
            if(Hash::check($request->passwordOld, $passwordOldInDatabase)) {
                $user = User::find($id)->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'password' => Hash::make($request->password)
                ]);
            } else {
                return back()->withErrors([
                    'error' => 'Password Lama Tidak Sesuai'
                ]);
            }
        } else {
            $user = User::find($id)->update([
                'name' => $request->name,
                'email' => $request->email,
            ]);
        }

        return redirect()->route('user.index')->with('status', 'Data User Berhasil Di Update');
    }
}

perpustakaan/app/Http/Controllers/Student/UserController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Student;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        return view('dashboard-student.user.index');
    }

    public function edit($id)
    {
        return view('dashboard-student.user.edit');
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'nama' => 'required',
            'nis' => 'required',
            'kelas' => 'required',
            'password' => 'nullable',
        ]);

        if($request->password) {
            $user = Student::find($id)->update([
                'nama' => $request->nama,
                'nis' => $request->nis,
                'kelas' => $request->kelas,
                'password' => Hash::make($request->password),
            ]);
        }

        $user = Student::find($id)->update([
            'nama' => $request->nama,
            'nis' => $request->nis,
            'kelas' => $request->kelas,
        ]);

        return redirect()->route('user-student.index')->with('status', 'Akun Anda Berhasil Di Update');
    }
}

perpustakaan/resources/views/dashboard-student/user/edit.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Edit Akun')
    
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card shadow">
            <div class="card-header">
                <h4>Edit Akun</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('user-student.update', Auth::guard('student')->user()->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="nama" class="form-label">Nama</label>
                            <input type="text" name="nama" value="{{ Auth::guard('student')->user()->nama }}" id="nama" class="form-control @error('nama') is-invalid @enderror">
                            @error('nama')
                                <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-6">
                            <label for="nis" class="form-label">NIS</label>
                            <input type="number" name="nis" value="{{ Auth::guard('student')->user()->nis }}" id="nis" class="form-control @error('nis') is-invalid @enderror">
                            @error('nis')
                                <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="kelas" class="form-label">Kelas</label>
                            <input type="text" name="kelas" value="{{ Auth::guard('student')->user()->kelas }}" id="kelas" class="form-control @error('kelas') is-invalid @enderror" readonly>
                            @error('kelas')
                                <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="col-md-6">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" id="email" class="form-control @error('password') is-invalid @enderror" placeholder="Masukkan password atau kosongkan">
                            @error('password')
                                <div class="alert alert-danger mt-2 mb-2 p-2">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <a href="{{ route('user-student.index') }}" class="btn btn-secondary float-end ms-3">Kembali</a>
                            <button type="submit" class="btn btn-primary float-end">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

perpustakaan/resources/views/dashboard-student/user/index.blade.php
@extends('layouts.dashboard-student')
@section('title', 'Student | Akun')

@section('content')
    <div class="row mb-3">
        <div class="col-12">
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ session('status') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-header">
                    <h4>Akun</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>NIS</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ Auth::guard('student')->user()->nama }}</td>
                                    <td>{{ Auth::guard('student')->user()->nis }}</td>
                                    <td>{{ Auth::guard('student')->user()->kelas }}</td>
                                    <td width="5%">
                                        <a href="{{ route('user-student.edit', Auth::guard('student')->user()->id) }}"
                                            class="btn btn-warning">
                                            <i class="fa-regular fa-pen-to-square"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection