perpustakaan/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LoginStudentController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Dashboard\BookController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\BorrowController;
use App\Http\Controllers\Dashboard\ReturnController;
use App\Http\Controllers\Dashboard\StudentController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\CategoryBookController;
use App\Http\Controllers\Student\BookController as StudentBookController;
use App\Http\Controllers\Student\BorrowHistoryController;
use App\Http\Controllers\Student\DashboardController as StudentDashboardController;
use App\Http\Controllers\Student\UserController as StudentUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/book', [HomeController::class, 'book'])->name('book');
Route::get('/book/detail/{slug}', [HomeController::class, 'detail_book'])->name('detail-book');
Route::get('/category-book/{id}', [HomeController::class, 'category_book'])->name('category-book');
Route::get('/search-book', [HomeController::class, 'search_book'])->name('search-book');

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register-student', [RegisterController::class, 'registerProcess'])->name('registerProcess');

Route::get('/login-student', [LoginStudentController::class, 'login'])->name('login-student');
Route::post('/authenticate-student', [LoginStudentController::class, 'authenticate'])->name('authenticate-student');

Route::group(['middleware' => ['auth:user']], function() {
    Route::prefix('/admin')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.admin');
        Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

        Route::resource('/category-book', CategoryBookController::class);
        Route::resource('/book', BookController::class);
        Route::resource('/student', StudentController::class);
        Route::resource('/borrow', BorrowController::class);
        Route::resource('/user', UserController::class);
        Route::resource('/return', ReturnController::class);
    });
});

Route::group(['middleware' => ['auth:student']], function() {
    Route::prefix('/student')->group(function() {
        Route::get('/dashboard', [StudentDashboardController::class, 'index'])->name('dashboard.siswa');
        Route::post('/logout-student', [LoginStudentController::class, 'logout'])->name('logout-student');

        Route::resource('/user-student', StudentUserController::class);
        Route::resource('/book-student', StudentBookController::class);
        Route::resource('/borrow-history', BorrowHistoryController::class);
    });
});

perpustakaan/resources/views/splitters/footer.blade.php
<div class="py-6 px-6 text-center">
  <p class="mb-0 fs-4">Developed by <b>Matthew Christian Cahyadi</b></p>
</div>

perpustakaan/resources/views/splitters/header.blade.php
<header class="app-header">
     <nav class="navbar navbar-expand-lg navbar-light">
       <ul class="navbar-nav">
         <li class="nav-item d-block d-xl-none">
           <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
             <i class="ti ti-menu-2"></i>
           </a>
         </li>
         <li class="nav-item">
           <a class="nav-link nav-icon-hover" href="javascript:void(0)">
             <i class="ti ti-bell-ringing"></i>
             <div class="notification bg-primary rounded-circle"></div>
           </a>
         </li>
       </ul>
       <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
         <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
          <h4 class="text-center mt-2">{{ Auth::user()->name }}</h4>
           <li class="nav-item dropdown">
             <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
               aria-expanded="false">
               <img src="{{ url('assets/images/profile/user-1.jpg') }}" alt="" width="35" height="35" class="rounded-circle">
             </a>
             <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
               <div class="message-body">
                 {{-- <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                   <i class="ti ti-user fs-6"></i>
                   <p class="mb-0 fs-3">My Profile</p>
                 </a>
                 <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                   <i class="ti ti-mail fs-6"></i>
                   <p class="mb-0 fs-3">My Account</p>
                 </a>
                 <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                   <i class="ti ti-list-check fs-6"></i>
                   <p class="mb-0 fs-3">My Task</p>
                 </a> --}}
                 <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</button>
                 </form>
               </div>
             </div>
           </li>
         </ul>
       </div>
     </nav>
   </header>

perpustakaan/resources/views/splitters/main.blade.php
@yield('content')

perpustakaan/resources/views/splitters/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div>
      <div class="brand-logo d-flex align-items-center justify-content-between">
        <h3 class="text-center">Perpustakaan</h3>
        <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
          <i class="ti ti-x fs-8"></i>
        </div>
      </div>
      <!-- Sidebar navigation-->
      <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
        <ul id="sidebarnav">
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Home</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/dashboard*')) ? 'active' : '' }}" href="{{ route('dashboard.admin') }}" aria-expanded="false">
              <span>
                <i class="ti ti-layout-dashboard"></i>
              </span>
              <span class="hide-menu">Dashboard</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">UI COMPONENTS</span>
          </li>
          {{-- <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/profile*')) ? 'active' : '' }}" href="{{ route('profile.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-article"></i>
              </span>
              <span class="hide-menu">Profile</span>
            </a>
          </li> --}}
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/category-book*')) ? 'active' : '' }}" href="{{ route('category-book.index') }}" aria-expanded="false">
              <span>
                <i class="fa-solid fa-bookmark fs-5"></i>
              </span>
              <span class="hide-menu">Kategori Buku</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/book*')) ? 'active' : '' }}" href="{{ route('book.index') }}" aria-expanded="false">
              <span>
                <i class="fa-solid fa-book fs-5"></i>
              </span>
              <span class="hide-menu">Buku</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/student*')) ? 'active' : '' }}" href="{{ route('student.index') }}" aria-expanded="false">
              <span>
                <i class="fa-solid fa-user fs-5"></i>
              </span>
              <span class="hide-menu">Siswa</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/borrow*')) ? 'active' : '' }}" href="{{ route('borrow.index') }}" aria-expanded="false">
              <span>
                <i class="fa-solid fa-hand-point-right fs-5"></i>
                {{-- <i class="fa-solid fa-clipboard-user fs-5"></i> --}}
              </span>
              <span class="hide-menu">Peminjaman</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/return*')) ? 'active' : '' }}" href="{{ route('return.index') }}" aria-expanded="false">
              <span>
                <i class="fa-solid fa-hand-point-left fs-5"></i>
              </span>
              <span class="hide-menu">Pengembalian</span>
            </a>
          </li>
          {{-- <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/studi-program*')) ? 'active' : '' }}" href="{{ route('study-program.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-typography"></i>
              </span>
              <span class="hide-menu">Program Studi</span>
            </a>
          </li> --}}
          {{-- <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/student*')) ? 'active' : '' }}" href="{{ route('student.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-typography"></i>
              </span>
              <span class="hide-menu">Mahasiswa</span>
            </a>
          </li> --}}
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">AUTH</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/user*')) ? 'active' : '' }}" href="{{ route('user.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-login"></i>
              </span>
              <span class="hide-menu">Akun</span>
            </a>
          </li>
          {{-- <li class="sidebar-item">
            <a class="sidebar-link {{ (request()->is('admin/borrow*')) ? 'active' : '' }}" href="{{ route('borrow.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-user-plus"></i>
              </span>
              <span class="hide-menu">Peminjaman</span>
            </a>
          </li> --}}
        </ul>
      </nav>
      <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
  </aside>